[tools]
wally = "UpliftGames/wally@0.3.2"
rojo = "rojo-rbx/rojo@7.4.0-rc2"
selene = "Kampfkarren/selene@0.25.0"
StyLua = "JohnnyMorganz/StyLua@0.18.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.2.1"
