[tools]
wally = "UpliftGames/wally@0.3.2"
rojo = "rojo-rbx/rojo@7.4.4"
selene = "Kampfkarren/selene@0.27.1"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.2"
Stylua = "JohnnyMorganz/Stylua@2.0.2"
