[package]
name = "jackc/cloudent-project"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
React = "jsdotlua/react@17.0.2"
ReactRoblox = "jsdotlua/react-roblox@17.0.2"
ReactRodux = "solarhorizon/react-rodux@0.2.2"
Rodux = "roblox/rodux@3.0.0"
t = "osyrisrblx/t@3.0.0"
Sift = "csqrl/sift@0.0.8"
Maid = "chipioindustries/maid@1.0.1"
Reflex = "littensy/reflex@4.2.2" # Just so I can use some handy selector APIs
